export interface SpecType {
    regex: RegExp;
    type: TokenType;
}

export interface Token {
    type: TokenType;
    value: any;
}

export enum TokenType {
    SKIP = "SKIP",
    SOFTWARE_HEADER = "SOFTWARE_HEADER",
    MIDI_NOTE_MAPPINGS_HEADER = "MIDI_NOTE_MAPPINGS_HEADER",
    FREQUENCY_MAPPINGS_HEADER = "FREQUENCY_MAPPINGS_HEADER",
    INSTRUMENT_MAPPINGS_HEADER = "INSTRUMENT_MAPPINGS_HEADER",
    GRACENOTE_DURATIONS_HEADER = "GRACENOTE_DURATIONS_HEADER",
    FONT_SIZES_HEADER = "FONT_SIZES_HEADER",
    TUNE_FORMAT_HEADER = "TUNE_FORMAT_HEADER",
    TUNE_TEMPO_HEADER = "TUNE_TEMPO_HEADER",
    TEXT_TAG = "TEXT_TAG",
    CLEF = "CLEF",
    KEY_SIGNATURE = "KEY_SIGNATURE",
    TIME_SIGNATURE = "TIME_SIGNATURE",
    PART_BEGINNING = "PART_BEGINNING",
    PART_END = "PART_END",
    MELODY_NOTE = "MELODY_NOTE",
    REST = "REST",
    DOTTED_NOTE = "DOTTED_NOTE",
    GRACENOTE = "GRACENOTE",
    DOUBLING = "DOUBLING",
}
