let embellishmentMap = new Map<string, string>([
    ["db", "doubling"],
    ["tdb", "thumb-doubling"],
    ["hdb", "half-doubling"],
    ["str", "strike"],
    ["gst", "g-gracenote-strike"],
    ["lgst", "heavy-g-gracenote-strike"],
    ["tst", "thumb-strike"],
    ["ltst", "heavy-thumb-strike"],
    ["hst", "half-strike"],
    ["lhst", "heavy-half-strike"],
    ["grp", "grip"],
    ["hgrp", "half-grip"],
    ["grpb", "b-grip"],
    ["ggrp", "g-gracenote-grip"],
    ["ggrpdb", "g-gracenote-b-grip"],
    ["tgrp", "thumb-grip"],
    ["tgrpdb", "thumb-b-grip"],
    ["hgrpdb", "half-b-grip"],
    ["tar", "taorluath"],
    ["tarb", "b-taorluath"],
    ["bubly", "bubbly-note"],
    ["hbubly", "half-bubbly-note"],
    ["brl", "birl"],
    ["abr", "a-birl"],
    ["gbr", "g-gracenote-birl"],
    ["tbr", "thumb-birl"],
    ["thrd", "throw"],
    ["hvthrd", "heavy-throw"],
    ["hthrd", "half-throw"],
    ["hhvthrd", "half-heavy-throw"],
    ["pel", "pele"],
    ["lpel", "closed-pele"],
    ["tpel", "thumb-pele"],
    ["ltpel", "closed-thumb-pele"],
    ["hpel", "half-pele"],
    ["lhpel", "closed-half-pele"],
]);

export default embellishmentMap;
